package com.app.rc.getting_started_with_swagger.ui.model.response;

import io.swagger.annotations.ApiModelProperty;
import lombok.*;

/**
 *
 */
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class BookTicketsResponseModel {

    @ApiModelProperty(
            value = "UUID of the Record",
            notes = "UUID is generated by the Service itself",
            dataType = "java.lang.Integer",
            position = 1
    )
    private long id;

    @ApiModelProperty(
            value = "Identifier for Booking",
            notes = "Booking ID can be used for Look-up",
            dataType = "Long",
            position = 2
    )
    private long ticketId;

    @ApiModelProperty(
            value = "Status of record whether it is active or not",
            notes = "If status is false, record is invalid and is not under use",
            dataType = "java.lang.Boolean",
            position = 3,
            hidden = true
    )
    private boolean status;
}